name: CI

on:
  push:
    branches: [ main ]
    
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      
      - name: install nodeJs
        uses: actions/setup-node@v2.5.1
        with: 
            node-version: "14.X"
                
        
      - name: install deps
        run: |
          cd bbq-fore
          npm install
        
      - name: build app
        run: |
          cd bbq-fore
          npm run build
        
      - name: copy dist file with scp
        uses: appleboy/scp-action@master
        with: 
          host: ${{secrets.HOST}}
          username: root
          password: ${{secrets.PASSWORD}}
          port: 22
          source: "bbq-fore/dist"
          target: "/root"
          rm: false
          
      - name: deploy fore
        uses: appleboy/ssh-action@master
        with: 
          host: ${{secrets.HOST}}
          username: root
          password: ${{secrets.PASSWORD}}
          script: |
            cp -r /root/bbq-fore/dist /root/nginx
            rm -rf /root/bbq-fore
            rm -rf /root/nginx/html
            cd /root/nginx/
            mv dist html
            cd /home/docker/
            docker-compose restart nginx
