name: CI

on:
  push:
    branches: [ main ]
    
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: action/checkout@v2
      
      - name: install nodeJs
        uses: actions/setup-node@v2.5.1
        with: 
            node-version: "14.X"
            
      - name: install deps
        run: npm install
        
      - name: build app
        run: npm run build
        
      - name: copy dist file with scp
        uses: appleboy/scp-action@0.0.1
        with: 
          host: ${{secrets.HOST}}
          username: root
          password: ${{secrets.PASSWORD}}
          port: 22
          source: "/"
          target: "/root"
